on:
  push:

jobs:
  npm_install_and_k6:
    name: Install dependencies and run k6 test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Run k6 cloud test
      uses: grafana/k6-action@v0.3.1
      with:
        filename: loadtest.js
        flags: --vus 50 --duration 10s
        cloud: true
        token: ${{ secrets.K6_CLOUD_API_TOKEN }}
