name: Selenium Test Grid

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium-chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
      selenium-firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444
      selenium-edge:
        image: selenium/standalone-edge
        ports:
          - 4446:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install selenium-webdriver

    - name: Run tests
      run: node tests2/addProfileGrid.js
 